import { useEffect, useState, useCallback, useMemo } from "react";
import {
  Phone, RefreshCw, Plus, Check, Trash2, X,
  PhoneCall, RotateCcw, CreditCard, FileText,
  Users, CalendarCheck, Search, TrendingUp,
} from "lucide-react";
import Sidebar from "../../components/Sidebar/Sidebar";
import LeadDrawer from "../../Leads/LeadDrawer";
import { toast } from "../../utils/toast";
import "./TodaysPlanPage.css";

const API = import.meta?.env?.VITE_API_BASE_URL || "http://localhost:5000";
function auth(extra = {}) {
  const t = localStorage.getItem("nnc_token");
  return { ...(t ? { Authorization: `Bearer ${t}` } : {}), ...extra };
}

const SECTIONS = [
  { key: "new_call",  label: "New Calls",   icon: PhoneCall,    color: "#ef4444", light: "#fef2f2" },
  { key: "follow_up", label: "Follow-ups",  icon: RotateCcw,    color: "#f59e0b", light: "#fffbeb" },
  { key: "payment",   label: "Payments",    icon: CreditCard,    color: "#10b981", light: "#ecfdf5" },
  { key: "other",     label: "Other",       icon: FileText,      color: "#8b5cf6", light: "#f5f3ff" },
];

const TYPE_META = {
  new_call:   { label: "Call",       color: "#ef4444" },
  follow_up:  { label: "Follow-up",  color: "#f59e0b" },
  payment:    { label: "Payment",    color: "#10b981" },
  proposal:   { label: "Proposal",   color: "#8b5cf6" },
  meeting:    { label: "Meeting",    color: "#3b82f6" },
  onboarding: { label: "Onboarding", color: "#06b6d4" },
};

const P_COLOR = { urgent: "#ef4444", high: "#f59e0b", medium: "#3b82f6", low: "#d1d5db" };

const fmtDate = () => new Intl.DateTimeFormat("en-IN", {
  weekday: "long", day: "numeric", month: "long", year: "numeric",
}).format(new Date());

export default function TodaysPlanPage() {
  const [tasks,        setTasks]        = useState([]);
  const [loading,      setLoading]      = useState(false);
  const [activeTab,    setActiveTab]    = useState("new_call");
  const [addOpen,      setAddOpen]      = useState(false);
  const [drawerOpen,   setDrawerOpen]   = useState(false);
  const [drawerLeadId, setDrawerLeadId] = useState(null);

  const DONE_KEY = `tp_done_${new Date().toISOString().slice(0, 10)}`;
  const [doneIds, setDoneIds] = useState(() => {
    try { return new Set(JSON.parse(localStorage.getItem(DONE_KEY) || "[]")); }
    catch { return new Set(); }
  });
  useEffect(() => {
    try { localStorage.setItem(DONE_KEY, JSON.stringify([...doneIds])); } catch {}
  }, [doneIds]);

  const fetchTasks = useCallback(async () => {
    try {
      setLoading(true);
      const res  = await fetch(`${API}/api/today-plan/dashboard`, { headers: auth() });
      const json = await res.json();
      if (!res.ok || !json?.success) throw new Error(json?.message || "Failed");
      const { immediateTasks = [], scheduleTasks = [] } = json?.data?.sections || {};
      const seen = new Set();
      const all  = [...immediateTasks, ...scheduleTasks].filter(t => {
        if (seen.has(String(t._id))) return false;
        seen.add(String(t._id)); return true;
      });
      setTasks(all);
    } catch (e) { toast.error(e?.message || "Failed to load"); }
    finally { setLoading(false); }
  }, []);

  useEffect(() => { fetchTasks(); }, [fetchTasks]);

  const isDone = (t) => t.status === "completed" || doneIds.has(t._id);

  const markDone = async (task) => {
    if (task.isAutoGenerated || String(task._id).startsWith("auto-")) {
      setDoneIds(p => new Set([...p, task._id])); toast.success("Done!"); return;
    }
    try {
      const res  = await fetch(`${API}/api/today-plan/${task._id}/toggle`, { method: "PATCH", headers: auth() });
      const json = await res.json();
      if (!res.ok || !json?.success) throw new Error(json?.message);
      setTasks(prev => prev.map(t => t._id === task._id ? { ...t, status: json.data.status } : t));
      toast.success(json.data.status === "completed" ? "Done!" : "Marked pending");
    } catch (e) { toast.error(e?.message || "Failed"); }
  };

  const deleteTask = async (task) => {
    if (!window.confirm("Remove this task?")) return;
    if (task.isAutoGenerated || String(task._id).startsWith("auto-")) {
      setDoneIds(p => new Set([...p, task._id])); return;
    }
    try {
      const res  = await fetch(`${API}/api/today-plan/${task._id}`, { method: "DELETE", headers: auth() });
      const json = await res.json();
      if (!res.ok || !json?.success) throw new Error(json?.message);
      setTasks(prev => prev.filter(t => t._id !== task._id));
    } catch (e) { toast.error(e?.message || "Failed"); }
  };

  const OTHER = new Set(["proposal", "meeting", "onboarding"]);
  const grouped = useMemo(() => ({
    new_call:  tasks.filter(t => t.taskType === "new_call"),
    follow_up: tasks.filter(t => t.taskType === "follow_up"),
    payment:   tasks.filter(t => t.taskType === "payment"),
    other:     tasks.filter(t => OTHER.has(t.taskType)),
  }), [tasks]);

  const totalTasks = tasks.length;
  const doneTasks  = tasks.filter(t => isDone(t)).length;
  const pct        = totalTasks > 0 ? Math.round((doneTasks / totalTasks) * 100) : 0;

  const activeTasks   = (grouped[activeTab] || []).filter(t => !isDone(t));
  const completedTasks = (grouped[activeTab] || []).filter(t =>  isDone(t));

  const circumference = 2 * Math.PI * 28;
  const dashOffset    = circumference - (pct / 100) * circumference;

  return (
    <div className="tp2-layout">
      <Sidebar />
      <div className="tp2-main">

        {/* ── Top Bar ── */}
        <div className="tp2-topbar">
          <div>
            <div className="tp2-page-title">Today's Plan</div>
            <div className="tp2-page-date">{fmtDate()}</div>
          </div>
          <div className="tp2-topbar-right">
            <button className="tp2-refresh-btn" onClick={fetchTasks} disabled={loading}>
              <RefreshCw size={14} className={loading ? "tp2-spin" : ""} />
            </button>
            <button className="tp2-add-btn" onClick={() => setAddOpen(true)}>
              <Plus size={15} /> Add Task
            </button>
          </div>
        </div>

        {/* ── Dashboard Row ── */}
        <div className="tp2-dashboard">

          {/* Progress ring */}
          <div className="tp2-progress-card">
            <svg width="70" height="70" viewBox="0 0 70 70">
              <circle cx="35" cy="35" r="28" fill="none" stroke="#f1f5f9" strokeWidth="6" />
              <circle cx="35" cy="35" r="28" fill="none" stroke="#6366f1" strokeWidth="6"
                strokeDasharray={circumference} strokeDashoffset={dashOffset}
                strokeLinecap="round" transform="rotate(-90 35 35)"
                style={{ transition: "stroke-dashoffset .5s ease" }}
              />
              <text x="35" y="39" textAnchor="middle" fontSize="14" fontWeight="800" fill="#111827">{pct}%</text>
            </svg>
            <div>
              <div className="tp2-prog-label">Completed</div>
              <div className="tp2-prog-sub">{doneTasks} of {totalTasks} tasks</div>
            </div>
          </div>

          {/* Section summary cards */}
          {SECTIONS.map(s => {
            const Icon    = s.icon;
            const total   = grouped[s.key]?.length || 0;
            const pending = grouped[s.key]?.filter(t => !isDone(t)).length || 0;
            return (
              <button
                key={s.key}
                className={`tp2-sum-card ${activeTab === s.key ? "active" : ""}`}
                style={{ "--accent": s.color, "--light": s.light }}
                onClick={() => setActiveTab(s.key)}
              >
                <div className="tp2-sum-icon" style={{ background: s.light, color: s.color }}>
                  <Icon size={17} />
                </div>
                <div className="tp2-sum-body">
                  <div className="tp2-sum-count" style={{ color: s.color }}>{pending}</div>
                  <div className="tp2-sum-label">{s.label}</div>
                  {total - pending > 0 && <div className="tp2-sum-done">{total - pending} done</div>}
                </div>
              </button>
            );
          })}

        </div>

        {/* ── Task Panel ── */}
        <div className="tp2-panel">
          {/* Panel header */}
          {(() => {
            const sec = SECTIONS.find(s => s.key === activeTab);
            const Icon = sec.icon;
            return (
              <div className="tp2-panel-head" style={{ borderLeftColor: sec.color }}>
                <Icon size={15} color={sec.color} />
                <span className="tp2-panel-title">{sec.label}</span>
                <span className="tp2-panel-count" style={{ background: sec.color }}>
                  {activeTasks.length} pending
                </span>
                {completedTasks.length > 0 && (
                  <span className="tp2-panel-done">{completedTasks.length} done</span>
                )}
              </div>
            );
          })()}

          {/* Task rows */}
          <div className="tp2-rows">
            {activeTasks.length === 0 && completedTasks.length === 0 && (
              <div className="tp2-no-tasks">
                <TrendingUp size={32} color="#d1d5db" />
                <div>No tasks in this section</div>
              </div>
            )}

            {activeTasks.map(t => (
              <TaskRow key={t._id} task={t} done={false}
                onDone={markDone} onDelete={deleteTask}
                onOpenLead={id => { setDrawerLeadId(id); setDrawerOpen(true); }}
              />
            ))}

            {completedTasks.length > 0 && (
              <>
                <div className="tp2-divider">Completed</div>
                {completedTasks.map(t => (
                  <TaskRow key={t._id} task={t} done={true}
                    onDone={markDone} onDelete={deleteTask}
                    onOpenLead={id => { setDrawerLeadId(id); setDrawerOpen(true); }}
                  />
                ))}
              </>
            )}
          </div>
        </div>

      </div>

      {addOpen && (
        <AddTaskModal
          onClose={() => setAddOpen(false)}
          onCreated={task => { setTasks(p => [task, ...p]); setAddOpen(false); }}
        />
      )}

      <LeadDrawer open={drawerOpen} leadId={drawerLeadId} apiBase={API}
        onClose={() => { setDrawerOpen(false); setDrawerLeadId(null); }}
        onLeadUpdated={fetchTasks}
      />
    </div>
  );
}

/* ── Task Row (compact) ── */
function TaskRow({ task, done, onDone, onDelete, onOpenLead }) {
  const meta = TYPE_META[task.taskType] || TYPE_META.follow_up;
  return (
    <div className={`tp2-row ${done ? "tp2-row-done" : ""}`}>
      {/* Priority bar */}
      <div className="tp2-row-bar" style={{ background: P_COLOR[task.priority] || "#d1d5db" }} />

      {/* Main info */}
      <div className="tp2-row-info">
        <button
          className="tp2-row-name"
          onClick={() => task.leadId && onOpenLead(task.leadId)}
        >
          {task.title}
        </button>
        {task.subtitle && task.subtitle !== task.title && !task.subtitle.startsWith("Auto") && (
          <span className="tp2-row-sub">{task.subtitle}</span>
        )}
      </div>

      {/* Phone */}
      {task.phone && (
        <a href={`tel:${task.phone}`} className="tp2-row-phone" onClick={e => e.stopPropagation()}>
          <Phone size={11} /> {task.phone}
        </a>
      )}

      {/* Type badge */}
      <span className="tp2-row-type" style={{ color: meta.color, background: meta.color + "18" }}>
        {meta.label}
      </span>

      {/* Due */}
      <span className={`tp2-row-due ${task.dueLabel === "Overdue" ? "overdue" : task.dueLabel === "Today" || task.dueLabel === "ASAP" ? "today" : ""}`}>
        {task.dueLabel}
      </span>

      {/* Actions */}
      <div className="tp2-row-actions">
        {!done
          ? <button className="tp2-btn-done"  onClick={() => onDone(task)}   title="Mark done"><Check size={13} /></button>
          : <span   className="tp2-btn-ticked"><Check size={13} /></span>
        }
        <button className="tp2-btn-del" onClick={() => onDelete(task)} title="Remove"><Trash2 size={12} /></button>
      </div>
    </div>
  );
}

/* ── Add Task Modal ── */
function AddTaskModal({ onClose, onCreated }) {
  const [form, setForm] = useState({ title: "", taskType: "follow_up", priority: "medium", phone: "", notes: "", leadId: "" });
  const [saving, setSaving]       = useState(false);
  const [search, setSearch]       = useState("");
  const [leads,  setLeads]        = useState([]);
  const [searching, setSearching] = useState(false);
  const [picked, setPicked]       = useState(null);

  useEffect(() => {
    if (!search.trim()) { setLeads([]); return; }
    const t = setTimeout(async () => {
      try {
        setSearching(true);
        const res  = await fetch(`${API}/api/leads?q=${encodeURIComponent(search.trim())}&limit=6`, { headers: auth() });
        const json = await res.json();
        setLeads(json?.data || []);
      } catch {} finally { setSearching(false); }
    }, 300);
    return () => clearTimeout(t);
  }, [search]);

  const pickLead = (l) => {
    setPicked(l);
    setForm(p => ({ ...p, leadId: l._id, title: p.title || `Follow-up - ${l.name}`, phone: p.phone || l.phone || "" }));
    setSearch(""); setLeads([]);
  };

  const save = async () => {
    if (!form.title.trim()) { toast.warning("Title is required"); return; }
    try {
      setSaving(true);
      const res  = await fetch(`${API}/api/today-plan`, {
        method: "POST",
        headers: auth({ "Content-Type": "application/json" }),
        body: JSON.stringify({ ...form, plannedDate: new Date().toISOString() }),
      });
      const json = await res.json();
      if (!res.ok || !json?.success) throw new Error(json?.message || "Failed");
      toast.success("Task added!");
      onCreated(json.data);
    } catch (e) { toast.error(e?.message || "Failed"); }
    finally { setSaving(false); }
  };

  return (
    <div className="tp2-overlay" onClick={onClose}>
      <div className="tp2-modal" onClick={e => e.stopPropagation()}>
        <div className="tp2-modal-head">
          <span>Add Task</span>
          <button onClick={onClose}><X size={16} /></button>
        </div>
        <div className="tp2-modal-body">
          <div className="tp2-mf">
            <label>Title *</label>
            <input autoFocus placeholder="What needs to be done?" value={form.title}
              onChange={e => setForm(p => ({ ...p, title: e.target.value }))}
              onKeyDown={e => e.key === "Enter" && save()} />
          </div>
          <div className="tp2-mf-row">
            <div className="tp2-mf">
              <label>Type</label>
              <select value={form.taskType} onChange={e => setForm(p => ({ ...p, taskType: e.target.value }))}>
                <option value="new_call">New Call</option>
                <option value="follow_up">Follow-up</option>
                <option value="payment">Payment</option>
                <option value="proposal">Proposal</option>
                <option value="meeting">Meeting</option>
                <option value="onboarding">Onboarding</option>
              </select>
            </div>
            <div className="tp2-mf">
              <label>Priority</label>
              <select value={form.priority} onChange={e => setForm(p => ({ ...p, priority: e.target.value }))}>
                <option value="urgent">🔴 Urgent</option>
                <option value="high">🟠 High</option>
                <option value="medium">🔵 Medium</option>
                <option value="low">⚪ Low</option>
              </select>
            </div>
          </div>
          <div className="tp2-mf">
            <label>Link to Lead</label>
            {picked ? (
              <div className="tp2-picked">
                <span>{picked.name} · {picked.phone}</span>
                <button onClick={() => { setPicked(null); setForm(p => ({ ...p, leadId: "" })); }}><X size={12} /></button>
              </div>
            ) : (
              <div style={{ position: "relative" }}>
                <div className="tp2-search-row">
                  <Search size={13} color="#9ca3af" />
                  <input placeholder="Search lead…" value={search} onChange={e => setSearch(e.target.value)} />
                </div>
                {(leads.length > 0 || searching) && (
                  <div className="tp2-lead-drop">
                    {searching && <div className="tp2-drop-loading">Searching…</div>}
                    {leads.map(l => (
                      <div key={l._id} className="tp2-drop-item" onClick={() => pickLead(l)}>
                        <span className="tp2-drop-name">{l.name}</span>
                        <span className="tp2-drop-phone">{l.phone}</span>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            )}
          </div>
          <div className="tp2-mf">
            <label>Phone</label>
            <input placeholder="Contact number" value={form.phone}
              onChange={e => setForm(p => ({ ...p, phone: e.target.value }))} />
          </div>
          <div className="tp2-mf">
            <label>Notes</label>
            <textarea rows={2} placeholder="Any notes…" value={form.notes}
              onChange={e => setForm(p => ({ ...p, notes: e.target.value }))} />
          </div>
        </div>
        <div className="tp2-modal-foot">
          <button className="tp2-btn-cancel" onClick={onClose}>Cancel</button>
          <button className="tp2-btn-save" onClick={save} disabled={saving}>{saving ? "Saving…" : "Add Task"}</button>
        </div>
      </div>
    </div>
  );
}
